
## Data Science Track - Stage B.

Name: Courage Siameh

ID: 186c55fbefc1f000

## Machine Learning: Regression - Predicting Energy Efficiency Of Buildings
### Quiz Questions 17 - 25

In [1]:
#importing libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
#importing data from pc to colab
from google.colab import files
uploaded = files.upload()

Saving energydata_complete.csv to energydata_complete.csv

In [5]:
# Reading and displaying our dataset
energy_data = pd.read_csv("energydata_complete.csv")
energy_data.head()

,date,Appliances,lights,T1,RH_1,T2,RH_2,T3,RH_3,T4,...,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
0,2016-01-11 17:00:00,60,30,19.89,47.596667,19.2,44.790000,19.79,44.730000,19.000000,...,17.033333,45.53,6.600000,733.5,92.0,7.000000,63.000000,5.3,13.275433,13.275433
1,2016-01-11 17:10:00,60,30,19.89,46.693333,19.2,44.722500,19.79,44.790000,19.000000,...,17.066667,45.56,6.483333,733.6,92.0,6.666667,59.166667,5.2,18.606195,18.606195
2,2016-01-11 17:20:00,50,30,19.89,46.300000,19.2,44.626667,19.79,44.933333,18.926667,...,17.000000,45.50,6.366667,733.7,92.0,6.333333,55.333333,5.1,28.642668,28.642668
3,2016-01-11 17:30:00,50,40,19.89,46.066667,19.2,44.590000,19.79,45.000000,18.890000,...,17.000000,45.40,6.250000,733.8,92.0,6.000000,51.500000,5.0,45.410389,45.410389
4,2016-01-11 17:40:00,60,40,19.89,46.333333,19.2,44.530000,19.79,45.000000,18.890000,...,17.000000,45.40,6.133333,733.9,92.0,5.666667,47.666667,4.9,10.084097,10.084097

In [8]:
# gettinng info on the dataset
energy_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19735 entries, 0 to 19734
Data columns (total 29 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         19735 non-null  object
 1   Appliances   19735 non-null  int64
 2   lights       19735 non-null  int64
 3   T1           19735 non-null  float64
 4   RH_1         19735 non-null  float64
 5   T2           19735 non-null  float64
 6   RH_2         19735 non-null  float64
 7   T3           19735 non-null  float64
 8   RH_3         19735 non-null  float64
 9   T4           19735 non-null  float64
 10  RH_4         19735 non-null  float64
 11  T5           19735 non-null  float64
 12  RH_5         19735 non-null  float64
 13  T6           19735 non-null  float64
 14  RH_6         19735 non-null  float64
 15  T7           19735 non-null  float64
 16  RH_7         19735 non-null  float64
 17  T8           19735 non-null  float64
 18  RH_8         19735 non-null  float64
 19  T9           19735 non-null  float64
 20  RH_9         19735 non-null  float64
 21  T_out        19735 non-null  float64
 22  Press_mm_hg  19735 non-null  float64
 23  RH_out       19735 non-null  float64
 24  Windspeed    19735 non-null  float64
 25  Visibility   19735 non-null  float64
 26  Tdewpoint    19735 non-null  float64
 27  rv1          19735 non-null  float64
 28  rv2          19735 non-null  float64
dtypes: float64(26), int64(2), object(1)
memory usage: 4.4+ MB

In [6]:
# displaying 20 random observations from out dataset
energy_data.sample(20)

,date,Appliances,lights,T1,RH_1,T2,RH_2,T3,RH_3,T4,...,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
19680,2016-05-27 09:00:00,90,0,23.600000,47.200000,23.497143,45.897143,26.000000,40.400000,24.290000,...,22.890000,46.500000,15.100000,756.100000,82.000000,3.000000,61.000000,12.000000,16.576132,16.576132
7557,2016-03-04 04:30:00,50,0,21.200000,36.137143,19.183333,37.500000,20.937143,38.368571,19.500000,...,18.500000,41.064286,3.950000,742.800000,83.000000,7.000000,50.500000,1.250000,22.614916,22.614916
18492,2016-05-19 03:00:00,50,0,23.133333,41.000000,20.700000,43.790000,24.600000,39.400000,23.066667,...,22.500000,43.400000,8.100000,749.200000,97.000000,2.000000,26.000000,7.600000,28.472092,28.472092
1291,2016-01-20 16:10:00,70,0,17.500000,36.433333,16.500000,36.700000,18.000000,37.530000,16.390000,...,15.690000,35.790000,0.550000,760.300000,83.666667,2.000000,60.500000,-1.933333,44.951295,44.951295
1065,2016-01-19 02:30:00,40,0,19.700000,39.090000,18.356667,39.126667,19.790000,40.400000,19.166667,...,16.890000,40.260000,-4.400000,756.350000,89.500000,1.000000,42.000000,-5.900000,46.489608,46.489608
19079,2016-05-23 04:50:00,60,0,23.926667,47.433333,21.700000,49.826667,26.200000,44.400000,23.500000,...,23.290000,49.957143,10.900000,753.300000,95.000000,3.000000,57.666667,10.200000,21.096125,21.096125
10575,2016-03-25 03:30:00,60,0,21.500000,39.590000,18.917500,42.567500,22.290000,38.900000,20.100000,...,19.500000,43.200000,6.100000,754.500000,97.000000,4.500000,38.000000,5.600000,31.776277,31.776277
18869,2016-05-21 17:50:00,80,0,24.876364,46.609727,25.031532,42.853393,26.420273,41.566364,24.181982,...,23.105182,46.536364,22.850000,753.666667,53.166667,6.166667,40.000000,12.816667,12.970619,12.970619
15173,2016-04-26 01:50:00,50,0,21.290000,38.266667,18.500000,40.060000,21.700000,36.290000,21.200000,...,19.500000,38.200000,2.716667,748.816667,91.000000,2.833333,40.000000,1.400000,26.840489,26.840489
17344,2016-05-11 03:40:00,50,0,24.633333,47.230000,22.790000,49.590000,26.700000,43.290000,24.890000,...,24.071429,47.168571,14.533333,748.700000,95.333333,2.000000,32.666667,13.733333,4.471680,4.471680
5696,2016-02-20 06:20:00,50,0,19.100000,38.590000,17.500000,40.500000,20.600000,37.837143,17.700000,...,17.700000,42.700000,6.700000,753.900000,93.666667,9.333333,44.000000,5.733333,26.001314,26.001314
9148,2016-03-15 05:40:00,40,0,20.890000,35.500000,17.000000,41.590000,21.700000,35.790000,19.790000,...,19.390000,38.790000,-1.566667,765.966667,88.333333,1.000000,61.333333,-3.266667,22.695781,22.695781
9261,2016-03-16 00:30:00,60,20,21.390000,41.400000,18.500000,46.790000,20.790000,38.590000,21.133333,...,19.600000,38.530000,4.350000,764.500000,92.000000,3.000000,57.000000,3.100000,8.344572,8.344572
977,2016-01-18 11:50:00,40,0,19.600000,41.230000,18.290000,41.590000,19.790000,40.700000,19.066667,...,17.290000,38.290000,-1.533333,758.483333,75.000000,3.000000,40.000000,-5.466667,30.621162,30.621162
1109,2016-01-19 09:50:00,40,0,18.700000,40.590000,17.200000,41.030000,19.100000,39.760000,17.890000,...,16.600000,38.900000,-3.900000,757.283333,91.333333,1.000000,62.000000,-5.150000,19.194462,19.194462
5913,2016-02-21 18:30:00,500,20,21.666667,46.393333,20.790000,45.200000,21.600000,43.790000,22.200000,...,18.390000,46.790000,11.550000,754.800000,85.000000,10.500000,40.000000,9.150000,13.388716,13.388716
9723,2016-03-19 05:30:00,50,0,21.200000,37.090000,18.390000,40.200000,21.390000,36.500000,19.790000,...,19.700000,40.590000,4.600000,761.800000,88.000000,1.500000,65.000000,2.800000,24.858199,24.858199
13056,2016-04-11 09:00:00,60,0,21.890000,39.090000,20.650000,39.895000,22.890000,37.663333,21.463333,...,23.223333,35.500000,13.000000,749.800000,57.000000,6.000000,27.000000,4.500000,19.912812,19.912812
2241,2016-01-27 06:30:00,40,0,20.100000,44.900000,19.390000,44.172500,19.700000,44.000000,19.066667,...,17.230000,49.590000,10.300000,757.350000,80.500000,10.000000,34.500000,7.000000,2.233453,2.233453
17126,2016-05-09 15:20:00,60,0,25.290000,39.626667,26.700000,34.590000,26.275000,37.590000,25.133333,...,23.600000,41.000000,22.400000,752.700000,49.333333,3.000000,40.000000,11.233333,29.473810,29.473810

In [19]:
# displaying column names of the dataset, it appears they are vaguely labelled or defined.
# Renaming columns will prove effective in further understanding each column in this analysis
energy_data.columns

Index(['date', 'Appliances', 'lights', 'T1', 'RH_1', 'T2', 'RH_2', 'T3',
       'RH_3', 'T4', 'RH_4', 'T5', 'RH_5', 'T6', 'RH_6', 'T7', 'RH_7', 'T8',
       'RH_8', 'T9', 'RH_9', 'T_out', 'Press_mm_hg', 'RH_out', 'Windspeed',
       'Visibility', 'Tdewpoint', 'rv1', 'rv2'],
      dtype='object')

In [21]:
energy_data.shape

(19735, 29)

In [22]:
energy_data.describe()

,Appliances,lights,T1,RH_1,T2,RH_2,T3,RH_3,T4,RH_4,...,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
count,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,...,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000
mean,97.694958,3.801875,21.686571,40.259739,20.341219,40.420420,22.267611,39.242500,20.855335,39.026904,...,19.485828,41.552401,7.411665,755.522602,79.750418,4.039752,38.330834,3.760707,24.988033,24.988033
std,102.524891,7.935988,1.606066,3.979299,2.192974,4.069813,2.006111,3.254576,2.042884,4.341321,...,2.014712,4.151497,5.317409,7.399441,14.901088,2.451221,11.794719,4.194648,14.496634,14.496634
min,10.000000,0.000000,16.790000,27.023333,16.100000,20.463333,17.200000,28.766667,15.100000,27.660000,...,14.890000,29.166667,-5.000000,729.300000,24.000000,0.000000,1.000000,-6.600000,0.005322,0.005322
25%,50.000000,0.000000,20.760000,37.333333,18.790000,37.900000,20.790000,36.900000,19.530000,35.530000,...,18.000000,38.500000,3.666667,750.933333,70.333333,2.000000,29.000000,0.900000,12.497889,12.497889
50%,60.000000,0.000000,21.600000,39.656667,20.000000,40.500000,22.100000,38.530000,20.666667,38.400000,...,19.390000,40.900000,6.916667,756.100000,83.666667,3.666667,40.000000,3.433333,24.897653,24.897653
75%,100.000000,0.000000,22.600000,43.066667,21.500000,43.260000,23.290000,41.760000,22.100000,42.156667,...,20.600000,44.338095,10.408333,760.933333,91.666667,5.500000,40.000000,6.566667,37.583769,37.583769
max,1080.000000,70.000000,26.260000,63.360000,29.856667,56.026667,29.236000,50.163333,26.200000,51.090000,...,24.500000,53.326667,26.100000,772.300000,100.000000,14.000000,66.000000,15.500000,49.996530,49.996530

In [23]:
# value counts of dtypes
energy_data.dtypes.value_counts()

float64    26
int64       2
object      1
Name: count, dtype: int64

In [26]:
# checking mean of nuull values
energy_data.isnull().mean()

date           0.0
Appliances     0.0
lights         0.0
T1             0.0
RH_1           0.0
T2             0.0
RH_2           0.0
T3             0.0
RH_3           0.0
T4             0.0
RH_4           0.0
T5             0.0
RH_5           0.0
T6             0.0
RH_6           0.0
T7             0.0
RH_7           0.0
T8             0.0
RH_8           0.0
T9             0.0
RH_9           0.0
T_out          0.0
Press_mm_hg    0.0
RH_out         0.0
Windspeed      0.0
Visibility     0.0
Tdewpoint      0.0
rv1            0.0
rv2            0.0
dtype: float64

Question 17

In [28]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

# Splitting the data into features (X) and target variable (y)
X = energy_data[['T2']]
y = energy_data['T6']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a linear regression model
model = LinearRegression()

# Train the model on the training data
model.fit(X_train, y_train)

# Make predictions on the testing data
y_pred = model.predict(X_test)

# Calculating Root Mean Squared Error (RMSE)
rmse = mean_squared_error(y_test, y_pred, squared=False)

print("Root Mean Squared Error: {:.3f}".format(rmse))

Root Mean Squared Error: 3.633

Question 18.

In [29]:
from sklearn.metrics import mean_absolute_error
from sklearn.preprocessing import MinMaxScaler

# dropping the specified columns
energy_data.drop(columns=['date', 'lights'], inplace=True)

# Define features (X) and target variable (y)
X = energy_data.drop(columns=['Appliances'])
y = energy_data['Appliances']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Normalize the dataset using MinMaxScaler
scaler = MinMaxScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Create a linear regression model
model = LinearRegression()

# Train the model on the training data
model.fit(X_train_scaled, y_train)

# Make predictions on the training data
y_train_pred = model.predict(X_train_scaled)

# Calculate the Mean Absolute Error (MAE) for the training set
mae_train = mean_absolute_error(y_train, y_train_pred)

print("Mean Absolute Error (Training Set): {:.3f}".format(mae_train))

Mean Absolute Error (Training Set): 53.742

Question 19

In [30]:
# Calculate the Root Mean Squared Error (RMSE) for the training set
mse_train = mean_squared_error(y_train, y_train_pred)
rmse_train = np.sqrt(mse_train)
print("Root Mean Squared Error (Training Set): {:.3f}".format(rmse_train))

Root Mean Squared Error (Training Set): 95.216

Question 20

In [32]:
# Calculate the Mean Absolute Error (MAE) for the test set

# Make predictions on the test data
y_test_pred = model.predict(X_test_scaled)
mae_test = mean_absolute_error(y_test, y_test_pred)
print("Mean Absolute Error (Test Set): {:.3f}".format(mae_test))

Mean Absolute Error (Test Set): 53.643

Question 21

In [34]:
# Calculate the Root Mean Squared Error (RMSE) for the test set
mse_test = mean_squared_error(y_test, y_test_pred)
rmse_test = np.sqrt(mse_test)
print("Root Mean Squared Error (Test Set): {:.3f}".format(rmse_test))

Root Mean Squared Error (Test Set): 93.640

Question 23

In [39]:
from sklearn.linear_model import Ridge

# Create a Ridge regression model
ridge_model = Ridge()

# Train the model on the training data
ridge_model.fit(X_train_scaled, y_train)

# Make predictions on the test data
y_test_pred = ridge_model.predict(X_test_scaled)

# Calculate the mean squared error (MSE) for the test set
mse_test = mean_squared_error(y_test, y_test_pred)

# Calculate the Root Mean Squared Error (RMSE) for the test set
rmse_test = np.sqrt(mse_test)

print("Root Mean Squared Error (Test Set) - Ridge Regression: {:.3f}".format(rmse_test))

Root Mean Squared Error (Test Set) - Ridge Regression: 93.709

Question 24.

In [40]:
from sklearn.linear_model import Lasso
# Create a Lasso regression model with default parameters
lasso_model = Lasso()

# Train the model on the training data
lasso_model.fit(X_train, y_train)

# Obtain the feature weights
feature_weights = lasso_model.coef_

# Count the number of features with non-zero feature weights
non_zero_features = sum(feature_weights != 0)

print("Number of features with non-zero feature weights: ", non_zero_features)

Number of features with non-zero feature weights:  21

Question 25

In [41]:
# Calculate the mean squared error (MSE) for the test set
mse_test = mean_squared_error(y_test, y_test_pred)

# Calculate the Root Mean Squared Error (RMSE) for the test set
rmse_test = np.sqrt(mse_test)

print("Root Mean Squared Error (Test Set) - Lasso Regression: {:.3f}".format(rmse_test))

Root Mean Squared Error (Test Set) - Lasso Regression: 93.709